### PR TITLE
SERV-6924 Socketchild

### PR DESCRIPTION
**Pull request by benoittoulme**

### CODE REVIEW

**Comment by arohter** [comment]
We're not using master ;)

**Comment by benoittoulme** [comment]
`// ListenAndServe, exits the process when the trackerListener is closed
func ListenAndServeWithExit(handler http.Handler, trackerListener *TrackingListener) (err error) {
	ListenAndServe(handler, trackerListener)
	os.Exit(0)
}`

**Comment by benoittoulme** [comment]
```golang
// ListenAndServe, exits the process when the trackerListener is closed
func ListenAndServeWithExit(handler http.Handler, trackerListener *TrackingListener) (err error) {
	ListenAndServe(handler, trackerListener)
	os.Exit(0)
}
```

**Comment by yingnanliu** [comment]
Looks good.

:alien: 
:bike:

**Pull request merged**
